"""FastAPI authentication middleware.

Verifies HS256 JWTs generated by Next.js Auth.js.
Shared secret: AUTH_SECRET env var (same on Railway and Vercel).
"""
from __future__ import annotations

import os
from functools import lru_cache

from fastapi import Depends, HTTPException
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import JWTError, jwt

_ALGORITHM = "HS256"
_ALL_PERMS = ["vbn:check", "vbn:fix", "products:create", "photos:upload", "admin:manage"]

_bearer = HTTPBearer(auto_error=False)


@lru_cache(maxsize=1)
def _secret() -> str:
    return os.getenv("AUTH_SECRET", "")


def _dev_payload() -> dict:
    """Used when AUTH_SECRET is not configured — grants all permissions."""
    return {"sub": "dev", "username": "dev", "permissions": _ALL_PERMS}


import logging as _logging
_mw_log = _logging.getLogger(__name__)

def get_token_payload(
    credentials: HTTPAuthorizationCredentials | None = Depends(_bearer),
) -> dict:
    """Verify JWT and return payload. Raises 401 if missing/invalid."""
    secret = _secret()
    if not secret:
        _mw_log.warning(
            "AUTH_SECRET is not set — running in INSECURE dev mode (all permissions granted). "
            "Set AUTH_SECRET on Railway to enable authentication."
        )
        return _dev_payload()
    if not credentials:
        raise HTTPException(status_code=401, detail="Authentication required")
    try:
        return jwt.decode(credentials.credentials, secret, algorithms=[_ALGORITHM])
    except JWTError as exc:
        raise HTTPException(status_code=401, detail="Invalid or expired token") from exc


def require_permission(perm: str):
    """Returns a FastAPI dependency that verifies the token and checks *perm*.

    Use perm="" to require authentication only (no specific permission check).
    """
    def dependency(payload: dict = Depends(get_token_payload)) -> dict:
        if perm and perm not in payload.get("permissions", []):
            raise HTTPException(status_code=403, detail=f"Permission '{perm}' required")
        return payload

    return dependency


def require_any_permission(*perms: str):
    """Returns a dependency that passes if the token has ANY of the given perms."""
    def dependency(payload: dict = Depends(get_token_payload)) -> dict:
        user_perms = payload.get("permissions", [])
        if not any(p in user_perms for p in perms):
            raise HTTPException(status_code=403, detail=f"One of {list(perms)} required")
        return payload

    return dependency
